/* command defs */
#define STORE_COMMAND_PREFIX        "NVL5"
#define STORE_COMMAND_SEPERATOR     "."
#define STORE_COMMAND_SET      STORE_COMMAND_PREFIX STORE_COMMAND_SEPERATOR "SET"
#define STORE_COMMAND_GET      STORE_COMMAND_PREFIX STORE_COMMAND_SEPERATOR "GET"